// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Bin collection point address - as referenced in https://api.reading.gov.uk/v0.json#/components/schemas/Address'
type Address struct {
	AccountSiteId     *string `json:"AccountSiteId,omitempty"`
	AccountSiteUprn   *string `json:"AccountSiteUprn,omitempty"`
	SiteAddress2      *string `json:"SiteAddress2,omitempty"`
	SiteAddressPrefix *string `json:"SiteAddressPrefix,omitempty"`
	SiteEasting       *string `json:"SiteEasting,omitempty"`
	SiteId            *string `json:"SiteId,omitempty"`
	SiteLatitude      *string `json:"SiteLatitude,omitempty"`
	SiteLongitude     *string `json:"SiteLongitude,omitempty"`
	SiteNorthing      *string `json:"SiteNorthing,omitempty"`
	SiteShortAddress  *string `json:"SiteShortAddress,omitempty"`
}

// List of addresses - as referenced in https://api.reading.gov.uk/v0.json#/components/schemas/Addresses'
type Addresses = []Address

// Status defines model for Status.
type Status struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Success defines model for Success.
type Success = map[string]interface{}

// SubscribeJSONBody defines parameters for Subscribe.
type SubscribeJSONBody = Success

// SubscribeJSONRequestBody defines body for Subscribe for application/json ContentType.
type SubscribeJSONRequestBody = SubscribeJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /addresses/{postcode})
	GetAddresses(ctx echo.Context, postcode string) error

	// (POST /collection/subscribe)
	Subscribe(ctx echo.Context) error

	// (GET /collection/subscribe/{subscriptionId})
	GetSubscriptionDetails(ctx echo.Context, subscriptionId string) error

	// (GET /health)
	Health(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAddresses converts echo context to params.
func (w *ServerInterfaceWrapper) GetAddresses(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "postcode" -------------
	var postcode string

	err = runtime.BindStyledParameterWithLocation("simple", false, "postcode", runtime.ParamLocationPath, ctx.Param("postcode"), &postcode)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter postcode: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetAddresses(ctx, postcode)
	return err
}

// Subscribe converts echo context to params.
func (w *ServerInterfaceWrapper) Subscribe(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Subscribe(ctx)
	return err
}

// GetSubscriptionDetails converts echo context to params.
func (w *ServerInterfaceWrapper) GetSubscriptionDetails(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "subscriptionId" -------------
	var subscriptionId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "subscriptionId", runtime.ParamLocationPath, ctx.Param("subscriptionId"), &subscriptionId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter subscriptionId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetSubscriptionDetails(ctx, subscriptionId)
	return err
}

// Health converts echo context to params.
func (w *ServerInterfaceWrapper) Health(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Health(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/addresses/:postcode", wrapper.GetAddresses)
	router.POST(baseURL+"/collection/subscribe", wrapper.Subscribe)
	router.GET(baseURL+"/collection/subscribe/:subscriptionId", wrapper.GetSubscriptionDetails)
	router.GET(baseURL+"/health", wrapper.Health)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9SXX3PaOBDAv8qO7mbuhWCbmlB4I5dcygzTZkL71OmDkNdYjS250ppLJsN3v5HsxBjD",
	"5eGuaftm7P2/v12JRyZ0UWqFiiybPTIrMiy4f5wniUHrHxO0wsiSpFZsxi6kAqHzHIV7AaWWioDX0nAG",
	"3ILBFA0qgQlIBRlRaWdBwEs5NMgTqTbDjd4Oq7tgGw6/Wq1+C9oogiaEoPH/Bxuw0ugSDUmsAxNCV4pW",
	"knCRuBd4z4syRzZjkygex2zA6KF0Py0ZqTZsN9jX+VQa1dV6E4XhZBSPx8c0nUoTyqirtvoI14vl1Qr+",
	"XH5YXb2ge2MwlfddA++1wlNqV9yS+9lRiCfR2ygahqeUDstxHk+i6JTwkpOkKsGuyjgaxuMoDKfheRyf",
	"VNVqc0T3LBxOzyfT8/jtNIzGk1Pa77WhrJdbNBlNx/Hp3FaZNrTHZKs5X15e3cK7D59WVwP4azn/CNEA",
	"us0ZwO11BKP5bd/67vmNXn9FQZ6W2g0egX8pLYFOn3jH70A8euYlYeH9/24wZTP2bxqsTYIbwx98zYhT",
	"5Q10p0foum2pNgUnNmNS0ZtRWxepCDdonIkCreUbL90vmsFvlTSYsNnn2mYr/+VISVeVEE3nDr45Y1Kl",
	"ul/ruYL5zQJSbWCD5MYB1t3dkyBxmVtIjS7gtq40uEkXMncpSfKEXEi11tIZYwO2RWNr++HQzdJuwHSJ",
	"ipfSrYJhPV4lp8wHGzw3OngstSWX6s592CD1I75FqoyykPcooYwTFJxEBpQhbOQW3eqsDTIfguHOipth",
	"do3UMuiiMbxAQmPZ7POhz5vGiPPnTO/51GCQjMSt8yCdsMuLDZjihavLnv+2nWQqHDQHwbHWf3HCttSq",
	"mY9RGNZcKULla8LLMpfCZxM42NuD5SWeG2g9Ewcs3CzAotmiAVujlFZ5/gCmUqrZEgmmvMrpFYK5rD0B",
	"GqMNNNg35a6Mck8il/5M3Xn1oGU2sNXa2Vr7uXId6GO0ehJxlg6QV5pk2iRke+A8azYtRUsXOnn4/2rS",
	"jPGRojSuy85gknY8+hF+IY8ugLseZKNX6GsnhQ5mXNwp/XeOyQYTx1ocTl8DegVckNwi2P3IeO4OlQfA",
	"e2nJ/oroB4/7CS2S0xv1GslvtSeg3FJVdeZu13fqsuYWE9AKJFlYXB7bqvsdvqxNvrRfF5dPm7XrDJ3/",
	"bxUaicnx9drN8T8u2eiH8i8McqrR/5lGEc7AksxzKFElv8AxkCHPKTsJ+zv/GUSG4g5QJf6vVQ/jWop9",
	"x2O4vXscW0rP9wt/nXFT8HyP+JnLv9v9EwAA//8o6y1y7Q4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
